// Run: node scripts/gen_formulas.js
// Writes data/formulas.js with all formulas from formulas.md

const fs = require('fs');
const path = require('path');

const entries = [
  // ── Integration: Power Rule ──
  { id:"int-01", chapter:8, category:"Integration \u2014 Power Rule", name:"Constant rule",
    latex:"\\int a\\,dx = ax + C", use:"Integrating a constant",
    variables:"a \\in \\mathbb{R}", mistakes:"Forgetting + C" },
  { id:"int-02", chapter:8, category:"Integration \u2014 Power Rule", name:"Power rule",
    latex:"\\int x^n\\,dx = \\dfrac{x^{n+1}}{n+1} + C",
    use:"Any polynomial term, n \u2260 \u22121", variables:"n \\neq -1",
    mistakes:"Using when n = -1; that gives ln|x|" },
  { id:"int-03", chapter:8, category:"Integration \u2014 Power Rule", name:"Linear composition power rule",
    latex:"\\int (ax+b)^n\\,dx = \\dfrac{(ax+b)^{n+1}}{a(n+1)} + C",
    use:"Power of a linear expression, n \u2260 \u22121",
    variables:"n \\neq -1,\\; a \\neq 0", mistakes:"Forgetting to divide by a" },

  // ── Rational Functions ──
  { id:"int-04", chapter:8, category:"Integration \u2014 Rational Functions", name:"Reciprocal rule",
    latex:"\\int \\dfrac{1}{x}\\,dx = \\ln|x| + C", use:"1/x integrand",
    variables:"x \\neq 0", mistakes:"Dropping the absolute value" },
  { id:"int-05", chapter:8, category:"Integration \u2014 Rational Functions", name:"Reciprocal of linear",
    latex:"\\int \\dfrac{1}{ax+b}\\,dx = \\dfrac{1}{a}\\ln|ax+b| + C",
    use:"1/(ax+b) integrand", variables:"a \\neq 0", mistakes:"Forgetting the 1/a factor" },

  // ── Exponential ──
  { id:"int-06", chapter:8, category:"Integration \u2014 Exponential", name:"e^x rule",
    latex:"\\int e^x\\,dx = e^x + C", use:"Standard exponential",
    variables:"", mistakes:"None \u2014 the simplest integral" },
  { id:"int-07", chapter:8, category:"Integration \u2014 Exponential", name:"e^(ax+b) rule",
    latex:"\\int e^{ax+b}\\,dx = \\dfrac{1}{a}e^{ax+b} + C",
    use:"Exponential with linear exponent", variables:"a \\neq 0",
    mistakes:"Forgetting the 1/a factor" },
  { id:"int-08", chapter:8, category:"Integration \u2014 Exponential", name:"General base exponential",
    latex:"\\int a^{bx+d}\\,dx = \\dfrac{a^{bx+d}}{b\\ln a} + C",
    use:"Exponential with base a \u2260 e", variables:"a > 0,\\; a \\neq 1,\\; b \\neq 0",
    mistakes:"Forgetting ln a in denominator" },

  // ── Trig Functions ──
  { id:"int-09", chapter:9, category:"Integration \u2014 Trig Functions", name:"sin x",
    latex:"\\int \\sin x\\,dx = -\\cos x + C", use:"Basic sine integral",
    variables:"", mistakes:"Sign error \u2014 result is negative cos" },
  { id:"int-10", chapter:9, category:"Integration \u2014 Trig Functions", name:"sin(ax+b)",
    latex:"\\int \\sin(ax+b)\\,dx = -\\dfrac{\\cos(ax+b)}{a} + C",
    use:"Sine with linear argument", variables:"a \\neq 0",
    mistakes:"Forgetting 1/a and the minus sign" },
  { id:"int-11", chapter:9, category:"Integration \u2014 Trig Functions", name:"cos x",
    latex:"\\int \\cos x\\,dx = \\sin x + C", use:"Basic cosine integral",
    variables:"", mistakes:"None \u2014 positive result" },
  { id:"int-12", chapter:9, category:"Integration \u2014 Trig Functions", name:"cos(ax+b)",
    latex:"\\int \\cos(ax+b)\\,dx = \\dfrac{\\sin(ax+b)}{a} + C",
    use:"Cosine with linear argument", variables:"a \\neq 0", mistakes:"Forgetting 1/a" },
  { id:"int-13", chapter:9, category:"Integration \u2014 Trig Functions", name:"tan x",
    latex:"\\int \\tan x\\,dx = \\ln|\\sec x| + C = -\\ln|\\cos x| + C",
    use:"Tangent integral", variables:"", mistakes:"Both forms equivalent; note signs" },
  { id:"int-14", chapter:9, category:"Integration \u2014 Trig Functions", name:"cot x",
    latex:"\\int \\cot x\\,dx = \\ln|\\sin x| + C = -\\ln|\\csc x| + C",
    use:"Cotangent integral", variables:"", mistakes:"Both forms equivalent" },
  { id:"int-15", chapter:9, category:"Integration \u2014 Trig Functions", name:"sec x",
    latex:"\\int \\sec x\\,dx = \\ln|\\sec x + \\tan x| + C",
    use:"Secant integral", variables:"", mistakes:"Must be memorised" },
  { id:"int-16", chapter:9, category:"Integration \u2014 Trig Functions", name:"csc x",
    latex:"\\int \\csc x\\,dx = \\ln|\\csc x - \\cot x| + C",
    use:"Cosecant integral", variables:"", mistakes:"Note minus sign inside absolute value" },
  { id:"int-17", chapter:9, category:"Integration \u2014 Trig Functions", name:"sec x tan x",
    latex:"\\int \\sec x\\tan x\\,dx = \\sec x + C",
    use:"Recognise as derivative of sec x", variables:"", mistakes:"Confusing with integral of tan x" },
  { id:"int-18", chapter:9, category:"Integration \u2014 Trig Functions", name:"csc x cot x",
    latex:"\\int \\csc x\\cot x\\,dx = -\\csc x + C",
    use:"Recognise as derivative of -csc x", variables:"",
    mistakes:"Sign error \u2014 result is negative csc" },

  // ── Integration by Parts ──
  { id:"ibp-01", chapter:9, category:"Integration by Parts", name:"IBP formula",
    latex:"\\int u\\,dv = uv - \\int v\\,du",
    use:"Products of functions \u2014 use LIATE to choose u",
    variables:"LIATE: Log, Inverse trig, Algebraic, Trig, Exponential",
    mistakes:"Wrong choice of u leads to harder integral" },
  { id:"ibp-02", chapter:9, category:"Integration by Parts", name:"IBP \u2014 three factors",
    latex:"\\int u\\,v\\,dw = uvw - \\int vw\\,du - \\int uw\\,dv",
    use:"Triple product integration by parts", variables:"",
    mistakes:"Account for all three cross terms" },
  { id:"ibp-03", chapter:9, category:"Integration by Parts \u2014 Related", name:"e\u1d43\u02e3 sin(bx)",
    latex:"\\int e^{ax}\\sin(bx)\\,dx = \\dfrac{e^{ax}}{a^2+b^2}\\bigl[a\\sin bx - b\\cos bx\\bigr] + C",
    use:"IBP twice \u2014 exponential times sine", variables:"a^2 + b^2 \\neq 0",
    mistakes:"Forgetting to divide by a\u00b2+b\u00b2" },
  { id:"ibp-04", chapter:9, category:"Integration by Parts \u2014 Related", name:"e\u1d43\u02e3 cos(bx)",
    latex:"\\int e^{ax}\\cos(bx)\\,dx = \\dfrac{e^{ax}}{a^2+b^2}\\bigl[a\\cos bx + b\\sin bx\\bigr] + C",
    use:"IBP twice \u2014 exponential times cosine", variables:"a^2 + b^2 \\neq 0",
    mistakes:"Sine version has minus; cosine version has plus" },
  { id:"ibp-05", chapter:9, category:"Integration by Parts \u2014 Related", name:"x\u207f ln x",
    latex:"\\int x^n \\ln x\\,dx = \\dfrac{x^{n+1}}{n+1}\\ln x - \\dfrac{x^{n+1}}{(n+1)^2} + C",
    use:"Polynomial times log \u2014 set u = ln x", variables:"n \\neq -1",
    mistakes:"Denominator of 2nd term is (n+1)\u00b2, not n+1" },
  { id:"ibp-06", chapter:9, category:"Integration by Parts \u2014 Related", name:"x\u207f e\u1d43\u02e3 reduction",
    latex:"\\int x^n e^{ax}\\,dx = \\dfrac{x^n e^{ax}}{a} - \\dfrac{n}{a}\\int x^{n-1}e^{ax}\\,dx",
    use:"Reduction formula \u2014 polynomial times exponential",
    variables:"n \\in \\mathbb{Z}^+,\\; a \\neq 0",
    mistakes:"Apply repeatedly until exponent reaches 0" },

  // ── Trig Substitution ──
  { id:"tsub-01", chapter:9, category:"Trig Substitution", name:"Form \u221a(a\u00b2\u2212u\u00b2)",
    latex:"\\int \\sqrt{a^2-u^2}\\,du = \\dfrac{u}{2}\\sqrt{a^2-u^2}+\\dfrac{a^2}{2}\\sin^{-1}\\!\\left(\\tfrac{u}{a}\\right)+C",
    use:"Integrand contains \u221a(a\u00b2\u2212u\u00b2)",
    variables:"u=a\\sin\\theta,\\;du=a\\cos\\theta\\,d\\theta",
    mistakes:"Not converting dx and limits" },
  { id:"tsub-02", chapter:9, category:"Trig Substitution", name:"Form \u221a(a\u00b2+u\u00b2)",
    latex:"\\int \\sqrt{a^2+u^2}\\,du = \\dfrac{u}{2}\\sqrt{u^2+a^2}+\\dfrac{a^2}{2}\\ln\\!\\left|u+\\sqrt{u^2+a^2}\\right|+C",
    use:"Integrand contains \u221a(a\u00b2+u\u00b2)",
    variables:"u=a\\tan\\theta,\\;du=a\\sec^2\\theta\\,d\\theta",
    mistakes:"Confusing with \u221a(a\u00b2\u2212u\u00b2) form" },
  { id:"tsub-03", chapter:9, category:"Trig Substitution", name:"Form \u221a(u\u00b2\u2212a\u00b2)",
    latex:"\\int \\sqrt{u^2-a^2}\\,du = \\dfrac{u}{2}\\sqrt{u^2-a^2}-\\dfrac{a^2}{2}\\ln\\!\\left|u+\\sqrt{u^2-a^2}\\right|+C",
    use:"Integrand contains \u221a(u\u00b2\u2212a\u00b2)",
    variables:"u=a\\sec\\theta,\\;du=a\\sec\\theta\\tan\\theta\\,d\\theta",
    mistakes:"Note the minus sign before the ln term" },

  // ── Reduction Formulas ──
  { id:"red-01", chapter:9, category:"Reduction Formulas", name:"sin\u00b2x",
    latex:"\\int \\sin^2 x\\,dx = \\dfrac{x}{2} - \\dfrac{\\sin 2x}{4} + C",
    use:"Even power of sine \u2014 half-angle identity", variables:"",
    mistakes:"Coefficient is 1/4 on sin 2x" },
  { id:"red-02", chapter:9, category:"Reduction Formulas", name:"cos\u00b2x",
    latex:"\\int \\cos^2 x\\,dx = \\dfrac{x}{2} + \\dfrac{\\sin 2x}{4} + C",
    use:"Even power of cosine \u2014 half-angle identity", variables:"",
    mistakes:"Plus sign (opposite of sin\u00b2x)" },
  { id:"red-03", chapter:9, category:"Reduction Formulas", name:"tan\u00b2x",
    latex:"\\int \\tan^2 x\\,dx = \\tan x - x + C",
    use:"Use tan\u00b2x = sec\u00b2x \u2212 1", variables:"",
    mistakes:"Remember \u222fsec\u00b2x = tan x" },
  { id:"red-04", chapter:9, category:"Reduction Formulas", name:"cot\u00b2x",
    latex:"\\int \\cot^2 x\\,dx = -\\cot x - x + C",
    use:"Use cot\u00b2x = csc\u00b2x \u2212 1", variables:"", mistakes:"Both terms negative" },
  { id:"red-05", chapter:9, category:"Reduction Formulas", name:"sin\u207fx reduction",
    latex:"\\int \\sin^n x\\,dx = -\\dfrac{\\sin^{n-1}x\\cos x}{n} + \\dfrac{n-1}{n}\\int \\sin^{n-2}x\\,dx",
    use:"High power of sine \u2014 apply repeatedly", variables:"n \\geq 2",
    mistakes:"Coefficient (n\u22121)/n on remaining integral" },
  { id:"red-06", chapter:9, category:"Reduction Formulas", name:"cos\u207fx reduction",
    latex:"\\int \\cos^n x\\,dx = \\dfrac{\\cos^{n-1}x\\sin x}{n} + \\dfrac{n-1}{n}\\int \\cos^{n-2}x\\,dx",
    use:"High power of cosine \u2014 apply repeatedly", variables:"n \\geq 2",
    mistakes:"Leading term positive (opposite sign from sin\u207f)" },
  { id:"red-07", chapter:9, category:"Reduction Formulas", name:"tan\u207fx reduction",
    latex:"\\int \\tan^n x\\,dx = \\dfrac{\\tan^{n-1}x}{n-1} - \\int \\tan^{n-2}x\\,dx,\\quad n\\neq 1",
    use:"High power of tan", variables:"n \\neq 1", mistakes:"Remaining integral has minus sign" },
  { id:"red-08", chapter:9, category:"Reduction Formulas", name:"cot\u207fx reduction",
    latex:"\\int \\cot^n x\\,dx = -\\dfrac{\\cot^{n-1}x}{n-1} - \\int \\cot^{n-2}x\\,dx,\\quad n\\neq 1",
    use:"High power of cot", variables:"n \\neq 1", mistakes:"Both terms negative" },
  { id:"red-09", chapter:9, category:"Reduction Formulas", name:"sec\u207fx reduction",
    latex:"\\int \\sec^n x\\,dx = \\dfrac{\\sec^{n-2}x\\tan x}{n-1} + \\dfrac{n-2}{n-1}\\int \\sec^{n-2}x\\,dx,\\quad n\\neq 1",
    use:"High power of sec", variables:"n \\neq 1",
    mistakes:"Coefficients 1/(n\u22121) and (n\u22122)/(n\u22121)" },
  { id:"red-10", chapter:9, category:"Reduction Formulas", name:"csc\u207fx reduction",
    latex:"\\int \\csc^n x\\,dx = -\\dfrac{\\csc^{n-2}x\\cot x}{n-1} + \\dfrac{n-2}{n-1}\\int \\csc^{n-2}x\\,dx,\\quad n\\neq 1",
    use:"High power of csc", variables:"n \\neq 1",
    mistakes:"Leading term negative; mirrors sec reduction otherwise" },

  // ── Inverse Trig Integrals ──
  { id:"invt-01", chapter:9, category:"Inverse Trig Integrals", name:"1/(a\u00b2+u\u00b2)",
    latex:"\\int \\dfrac{du}{a^2+u^2} = \\dfrac{1}{a}\\tan^{-1}\\!\\left(\\tfrac{u}{a}\\right) + C",
    use:"Sum of squares in denominator", variables:"a > 0",
    mistakes:"Forgetting the 1/a out front" },
  { id:"invt-02", chapter:9, category:"Inverse Trig Integrals", name:"1/\u221a(a\u00b2\u2212u\u00b2)",
    latex:"\\int \\dfrac{du}{\\sqrt{a^2-u^2}} = \\sin^{-1}\\!\\left(\\tfrac{u}{a}\\right) + C",
    use:"\u221a(a\u00b2\u2212u\u00b2) in denominator", variables:"|u| < a",
    mistakes:"No 1/a factor here (unlike arctan)" },
  { id:"invt-03", chapter:9, category:"Inverse Trig Integrals", name:"1/(u\u221a(u\u00b2\u2212a\u00b2))",
    latex:"\\int \\dfrac{du}{u\\sqrt{u^2-a^2}} = \\dfrac{1}{a}\\sec^{-1}\\!\\left(\\tfrac{u}{a}\\right) + C",
    use:"u \u00d7 \u221a(u\u00b2\u2212a\u00b2) in denominator", variables:"|u| > a > 0",
    mistakes:"Check the 1/a factor" },

  // ── Inverse Trig Antiderivatives ──
  { id:"invt-10", chapter:9, category:"Inverse Trig Antiderivatives", name:"arcsin",
    latex:"\\int \\sin^{-1}u\\,du = u\\sin^{-1}u + \\sqrt{1-u^2} + C",
    use:"Antiderivative of arcsin", variables:"|u| \\leq 1",
    mistakes:"The \u221a(1\u2212u\u00b2) term is easy to forget" },
  { id:"invt-11", chapter:9, category:"Inverse Trig Antiderivatives", name:"arccos",
    latex:"\\int \\cos^{-1}u\\,du = u\\cos^{-1}u - \\sqrt{1-u^2} + C",
    use:"Antiderivative of arccos", variables:"|u| \\leq 1",
    mistakes:"Sign difference from arcsin: minus \u221a(1\u2212u\u00b2)" },
  { id:"invt-12", chapter:9, category:"Inverse Trig Antiderivatives", name:"arctan",
    latex:"\\int \\tan^{-1}u\\,du = u\\tan^{-1}u - \\ln\\sqrt{1+u^2} + C",
    use:"Antiderivative of arctan", variables:"",
    mistakes:"Logarithm of square root, not of 1+u\u00b2" },
  { id:"invt-13", chapter:9, category:"Inverse Trig Antiderivatives", name:"arccot",
    latex:"\\int \\cot^{-1}u\\,du = u\\cot^{-1}u + \\ln\\sqrt{1+u^2} + C",
    use:"Antiderivative of arccot", variables:"",
    mistakes:"Sign is positive (opposite to arctan)" },
  { id:"invt-14", chapter:9, category:"Inverse Trig Antiderivatives", name:"arcsec",
    latex:"\\int \\sec^{-1}u\\,du = u\\sec^{-1}u - \\ln\\left|u+\\sqrt{u^2-1}\\right| + C",
    use:"Antiderivative of arcsec", variables:"|u| > 1",
    mistakes:"Absolute value required inside log" },
  { id:"invt-15", chapter:9, category:"Inverse Trig Antiderivatives", name:"arccsc",
    latex:"\\int \\csc^{-1}u\\,du = u\\csc^{-1}u + \\ln\\left|u+\\sqrt{u^2-1}\\right| + C",
    use:"Antiderivative of arccsc", variables:"|u| > 1",
    mistakes:"Positive log (opposite sign to arcsec)" },

  // ── Integration of Logarithms ──
  { id:"log-01", chapter:9, category:"Integration of Logarithms", name:"log_d(ax+b)",
    latex:"\\int \\log_d(ax+b)\\,dx = \\dfrac{ax+b}{a}\\log_d\\!\\left(\\tfrac{ax+b}{e}\\right) + C",
    use:"Log base d of linear expression", variables:"a \\neq 0,\\; ax+b > 0",
    mistakes:"Use change-of-base if unsure: log_d(x) = ln(x)/ln(d)" },

  // ── Table: u\u00b2\u00b1a\u00b2 ──
  { id:"tbl-01", chapter:9, category:"Table \u2014 u\u00b2\u00b1a\u00b2", name:"1/(u\u00b2\u2212a\u00b2)",
    latex:"\\int \\dfrac{du}{u^2-a^2} = \\dfrac{1}{2a}\\ln\\left|\\dfrac{u-a}{u+a}\\right| + C",
    use:"Difference of squares denominator", variables:"u \\neq \\pm a",
    mistakes:"|u\u2212a| = |a\u2212u|, either order inside log" },
  { id:"tbl-02", chapter:9, category:"Table \u2014 u\u00b2\u00b1a\u00b2", name:"1/(a\u00b2\u2212u\u00b2)",
    latex:"\\int \\dfrac{du}{a^2-u^2} = \\dfrac{1}{2a}\\ln\\left|\\dfrac{u+a}{u-a}\\right| + C",
    use:"Flipped denominator variant", variables:"u \\neq \\pm a",
    mistakes:"Numerator/denominator inside log swapped vs. 1/(u\u00b2\u2212a\u00b2)" },
  { id:"tbl-03", chapter:9, category:"Table \u2014 u\u00b2\u00b1a\u00b2", name:"1/\u221a(u\u00b2\u00b1a\u00b2)",
    latex:"\\int \\dfrac{du}{\\sqrt{u^2 \\pm a^2}} = \\ln\\left|u+\\sqrt{u^2 \\pm a^2}\\right| + C",
    use:"Square-root denominator with \u00b1a\u00b2", variables:"", mistakes:"Result is ln, not arcsin" },
  { id:"tbl-04", chapter:9, category:"Table \u2014 u\u00b2\u00b1a\u00b2", name:"\u221a(u\u00b2\u00b1a\u00b2)/u\u00b2",
    latex:"\\int \\dfrac{\\sqrt{u^2\\pm a^2}}{u^2}\\,du = -\\dfrac{\\sqrt{u^2\\pm a^2}}{u} + \\ln\\left|u+\\sqrt{u^2\\pm a^2}\\right| + C",
    use:"\u221a(u\u00b2\u00b1a\u00b2) over u\u00b2", variables:"u \\neq 0",
    mistakes:"Two-term result \u2014 don't drop either term" },
  { id:"tbl-05", chapter:9, category:"Table \u2014 u\u00b2\u00b1a\u00b2", name:"u\u00b2/\u221a(u\u00b2\u00b1a\u00b2)",
    latex:"\\int \\dfrac{u^2}{\\sqrt{u^2\\pm a^2}}\\,du = \\dfrac{1}{2}\\left[u\\sqrt{u^2\\pm a^2} \\mp a^2\\ln\\left|u+\\sqrt{u^2\\pm a^2}\\right|\\right] + C",
    use:"u\u00b2 over \u221a(u\u00b2\u00b1a\u00b2)", variables:"",
    mistakes:"The \u2213 flips sign depending on + or \u2212 in radicand" },
  { id:"tbl-06", chapter:9, category:"Table \u2014 u\u00b2\u00b1a\u00b2", name:"1/(u\u00b2\u221a(u\u00b2\u00b1a\u00b2))",
    latex:"\\int \\dfrac{du}{u^2\\sqrt{u^2\\pm a^2}} = \\mp\\dfrac{\\sqrt{u^2\\pm a^2}}{a^2 u} + C",
    use:"u\u00b2 \u00d7 \u221a(u\u00b2\u00b1a\u00b2) in denominator", variables:"u \\neq 0",
    mistakes:"Sign determined by \u00b1 in radicand" },
  { id:"tbl-07", chapter:9, category:"Table \u2014 u\u00b2\u00b1a\u00b2", name:"1/(u\u00b2\u00b1a\u00b2)^(3/2)",
    latex:"\\int \\dfrac{du}{(u^2\\pm a^2)^{3/2}} = \\dfrac{\\pm u}{a^2\\sqrt{u^2\\pm a^2}} + C",
    use:"Three-halves power of (u\u00b2\u00b1a\u00b2)", variables:"a \\neq 0",
    mistakes:"Sign of numerator matches \u00b1 in denominator" },

  // ── Table: \u221a(a\u00b2\u2212u\u00b2) ──
  { id:"tbl-08", chapter:9, category:"Table \u2014 \u221a(a\u00b2\u2212u\u00b2)", name:"u\u00b2/\u221a(a\u00b2\u2212u\u00b2)",
    latex:"\\int \\dfrac{u^2}{\\sqrt{a^2-u^2}}\\,du = -\\dfrac{u}{2}\\sqrt{a^2-u^2}+\\dfrac{a^2}{2}\\sin^{-1}\\!\\left(\\tfrac{u}{a}\\right)+C",
    use:"u\u00b2 over \u221a(a\u00b2\u2212u\u00b2)", variables:"|u| < a",
    mistakes:"Two-term answer; leading term is negative" },
  { id:"tbl-09", chapter:9, category:"Table \u2014 \u221a(a\u00b2\u2212u\u00b2)", name:"1/(u\u00b2\u221a(a\u00b2\u2212u\u00b2))",
    latex:"\\int \\dfrac{du}{u^2\\sqrt{a^2-u^2}} = -\\dfrac{\\sqrt{a^2-u^2}}{a^2 u} + C",
    use:"u\u00b2 \u00d7 \u221a(a\u00b2\u2212u\u00b2) in denominator", variables:"0 < |u| < a",
    mistakes:"Negative result \u2014 don't drop the minus" },
  { id:"tbl-10", chapter:9, category:"Table \u2014 \u221a(a\u00b2\u2212u\u00b2)", name:"\u221a(a\u00b2\u2212u\u00b2)/u\u00b2",
    latex:"\\int \\dfrac{\\sqrt{a^2-u^2}}{u^2}\\,du = -\\dfrac{\\sqrt{a^2-u^2}}{u} - \\sin^{-1}\\!\\left(\\tfrac{u}{a}\\right) + C",
    use:"\u221a(a\u00b2\u2212u\u00b2) over u\u00b2", variables:"0 < |u| < a", mistakes:"Both terms negative" },

  // ── Table: \u221a(a+bu) ──
  { id:"tbl-20", chapter:9, category:"Table \u2014 \u221a(a+bu)", name:"u/\u221a(a+bu)",
    latex:"\\int \\dfrac{u}{\\sqrt{a+bu}}\\,du = \\dfrac{2bu-4a}{3b^2}\\sqrt{a+bu} + C",
    use:"u over square root of linear", variables:"b \\neq 0",
    mistakes:"Numerator factor is 2bu \u2212 4a, not just 2bu" },
  { id:"tbl-21", chapter:9, category:"Table \u2014 \u221a(a+bu)", name:"1/(u\u221a(a+bu)), a>0",
    latex:"\\int \\dfrac{du}{u\\sqrt{a+bu}} = \\dfrac{1}{\\sqrt{a}}\\ln\\left|\\dfrac{\\sqrt{a+bu}-\\sqrt{a}}{\\sqrt{a+bu}+\\sqrt{a}}\\right| + C",
    use:"Reciprocal \u00d7 \u221a(a+bu), a > 0", variables:"a > 0,\\; u > 0",
    mistakes:"Requires a > 0 for this form" },
  { id:"tbl-22", chapter:9, category:"Table \u2014 \u221a(a+bu)", name:"\u221a(a+bu)/u (reduction)",
    latex:"\\int \\dfrac{\\sqrt{a+bu}}{u}\\,du = 2\\sqrt{a+bu} + a\\int \\dfrac{du}{u\\sqrt{a+bu}}",
    use:"Recursive reduction for \u221a(a+bu)/u", variables:"",
    mistakes:"Apply tbl-21 for the remaining integral" },

  // ── Table: 1/(a+bu) ──
  { id:"tbl-30", chapter:9, category:"Table \u2014 1/(a+bu)", name:"u/(a+bu)",
    latex:"\\int \\dfrac{u}{a+bu}\\,du = \\dfrac{u}{b} - \\dfrac{a}{b^2}\\ln|a+bu| + C",
    use:"Linear numerator over linear denominator", variables:"b \\neq 0",
    mistakes:"Two terms: polynomial + log" },
  { id:"tbl-31", chapter:9, category:"Table \u2014 1/(a+bu)", name:"1/(u(a+bu))",
    latex:"\\int \\dfrac{du}{u(a+bu)} = \\dfrac{1}{a}\\ln\\left|\\dfrac{u}{a+bu}\\right| + C",
    use:"Partial fractions: 1/(u(a+bu))", variables:"a \\neq 0,\\; b \\neq 0",
    mistakes:"Verify with partial fractions" },
  { id:"tbl-32", chapter:9, category:"Table \u2014 1/(a+bu)", name:"1/(u\u00b2(a+bu))",
    latex:"\\int \\dfrac{du}{u^2(a+bu)} = \\dfrac{b}{a^2}\\ln\\left|\\dfrac{a+bu}{u}\\right| - \\dfrac{1}{au} + C",
    use:"u\u00b2 \u00d7 (a+bu) in denominator", variables:"a \\neq 0",
    mistakes:"Two terms with opposite structure" },
  { id:"tbl-33", chapter:9, category:"Table \u2014 1/(a+bu)", name:"u\u00b2/(a+bu)",
    latex:"\\int \\dfrac{u^2}{a+bu}\\,du = \\dfrac{1}{b}\\!\\left(\\dfrac{u^2}{2}-\\dfrac{au}{b}+\\dfrac{a^2}{b^2}\\ln|a+bu|\\right) + C",
    use:"Polynomial long division then integrate", variables:"b \\neq 0",
    mistakes:"Three-term result after polynomial division" },
  { id:"tbl-34", chapter:9, category:"Table \u2014 1/(a+bu)", name:"u\u00b2/(a+bu)\u00b2",
    latex:"\\int \\dfrac{u^2}{(a+bu)^2}\\,du = \\dfrac{1}{b^3}\\!\\left[bu - \\dfrac{a^2}{a+bu} - 2a\\ln|a+bu|\\right] + C",
    use:"Squared linear denominator with u\u00b2 numerator", variables:"b \\neq 0",
    mistakes:"Three-term result" },

  // ── Quadratic Denominator ──
  { id:"tbl-40", chapter:9, category:"Table \u2014 Quadratic Denominator", name:"1/(a+bu+cu\u00b2), b\u00b2<4ac",
    latex:"\\int \\dfrac{du}{a+bu+cu^2} = \\dfrac{2}{\\sqrt{4ac-b^2}}\\tan^{-1}\\!\\left(\\dfrac{2cu+b}{\\sqrt{4ac-b^2}}\\right)+C",
    use:"Irreducible quadratic denominator (b\u00b2 < 4ac)", variables:"b^2 < 4ac",
    mistakes:"Complete the square if formula not memorised" },
  { id:"tbl-41", chapter:9, category:"Table \u2014 Quadratic Denominator", name:"1/(a+bu+cu\u00b2), b\u00b2>4ac",
    latex:"\\int \\dfrac{du}{a+bu+cu^2} = \\dfrac{1}{\\sqrt{b^2-4ac}}\\ln\\left|\\dfrac{2cu+b-\\sqrt{b^2-4ac}}{2cu+b+\\sqrt{b^2-4ac}}\\right|+C",
    use:"Quadratic with two real roots (b\u00b2 > 4ac)", variables:"b^2 > 4ac",
    mistakes:"Use partial fractions when roots are obvious" },

  // ── Original preserved entries ──
  { id:"form-04", chapter:8, category:"Definite Integral", name:"Riemann Sum",
    latex:"\\int_a^b f(x)\\,dx = \\lim_{n\\to\\infty}\\sum_{i=1}^n f(x_i^*)\\Delta x",
    use:"Definition of definite integral", variables:"\\Delta x = (b-a)/n",
    mistakes:"Forgetting the limit" },
  { id:"form-05", chapter:8, category:"Area", name:"Area between curves",
    latex:"A = \\int_a^b [f(x)-g(x)]\\,dx", use:"When f(x) \u2265 g(x) on [a,b]",
    variables:"f upper curve, g lower curve", mistakes:"Not checking which is upper" },
  { id:"form-06", chapter:8, category:"Volume", name:"Disk Method",
    latex:"V = \\pi\\int_a^b [f(x)]^2\\,dx", use:"Rotation about x-axis",
    variables:"f(x) \\geq 0", mistakes:"Forgetting \\pi" },
  { id:"form-07", chapter:8, category:"Volume", name:"Washer Method",
    latex:"V = \\pi\\int_a^b\\left([f(x)]^2-[g(x)]^2\\right)dx",
    use:"Rotation with hole: f outer, g inner", variables:"f(x) \\geq g(x) \\geq 0",
    mistakes:"Squaring the difference instead of difference of squares" },
  { id:"form-10", chapter:10, category:"Improper Integrals", name:"Type I (infinite limit)",
    latex:"\\int_a^\\infty f(x)\\,dx = \\lim_{t\\to\\infty}\\int_a^t f(x)\\,dx",
    use:"Infinite upper limit", variables:"", mistakes:"Forgetting the limit notation" },
  { id:"form-11", chapter:11, category:"Series", name:"Geometric Series",
    latex:"\\sum_{n=0}^\\infty ar^n = \\dfrac{a}{1-r},\\quad |r|<1",
    use:"Sum of geometric series", variables:"a = first term, r = ratio",
    mistakes:"|r| must be strictly less than 1" },
  { id:"form-12", chapter:11, category:"Taylor Series", name:"Taylor Series",
    latex:"f(x) = \\sum_{n=0}^\\infty \\frac{f^{(n)}(a)}{n!}(x-a)^n",
    use:"Represent function as power series", variables:"a = centre",
    mistakes:"Not checking radius of convergence" },
  { id:"form-13", chapter:12, category:"Differential Equations", name:"Linear ODE integrating factor",
    latex:"\\mu(x) = e^{\\int P(x)\\,dx}",
    use:"Solve y' + P(x)y = Q(x)", variables:"",
    mistakes:"Forgetting the constant disappears in mu" },
  { id:"form-01", chapter:7, category:"Hyperbolic Functions", name:"sinh definition",
    latex:"\\sinh x = \\dfrac{e^x - e^{-x}}{2}", use:"Definition",
    variables:"x \\in \\mathbb{R}", mistakes:"Confusing with sin x" },
  { id:"form-02", chapter:7, category:"Hyperbolic Functions", name:"cosh definition",
    latex:"\\cosh x = \\dfrac{e^x + e^{-x}}{2}", use:"Definition",
    variables:"x \\in \\mathbb{R}", mistakes:"Note cosh x \u2265 1 always" },
  { id:"form-03", chapter:7, category:"Hyperbolic Identities", name:"Pythagorean identity",
    latex:"\\cosh^2 x - \\sinh^2 x = 1", use:"Fundamental identity",
    variables:"", mistakes:"Sign is opposite to trig: minus not plus" },
  { id:"form-08", chapter:9, category:"Integration Techniques", name:"Integration by Parts",
    latex:"\\int u\\,dv = uv - \\int v\\,du", use:"Products of functions",
    variables:"Choose u by LIATE", mistakes:"Wrong choice of u" },
  { id:"form-09", chapter:9, category:"Trig Substitution", name:"sqrt(a2-x2)",
    latex:"x = a\\sin\\theta,\\quad \\sqrt{a^2-x^2}=a\\cos\\theta",
    use:"Integrands with sqrt(a2-x2)", variables:"-pi/2 <= theta <= pi/2",
    mistakes:"Not converting dx and limits" }
];

const output = 'const formulasData = ' + JSON.stringify(entries, null, 2) + ';\n';
const dest = path.join(__dirname, '..', 'data', 'formulas.js');
fs.writeFileSync(dest, output, 'utf8');
console.log('Written ' + entries.length + ' formulas to ' + dest);
